name: causal-hub
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=py313h06a4308_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6a678d5_0
  - ipython=9.1.0=py313h06a4308_0
  - ipython_pygments_lexers=1.1.1=py313h06a4308_0
  - jedi=0.19.2=py313h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=15.1.0=h767d61c_2
  - libmpdec=4.0.0=h5eee18b_0
  - libopenblas=0.3.29=ha39b09d_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.6=py313h06a4308_0
  - maturin=1.8.3=py313he81eb93_0
  - ncurses=6.4=h6a678d5_0
  - numpy=2.2.4=py313h3a69d60_0
  - numpy-base=2.2.4=py313habf87d0_0
  - openssl=3.5.0=h7b32b05_1
  - parso=0.8.4=py313h06a4308_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pip=25.1=pyhc872135_2
  - prompt-toolkit=3.0.43=py313h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.19.1=py313h06a4308_0
  - python=3.13.2=hf623796_100_cp313
  - python_abi=3.13=0_cp313
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py313h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py313h06a4308_1
  - traitlets=5.14.3=py313h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.45.1=py313h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
