name: causal-hub
channels:
  - defaults
  - conda-forge
dependencies:
  - accessible-pygments=0.0.5
  - alabaster=0.7.16
  - asttokens=3.0.0
  - babel=2.16.0
  - beautifulsoup4=4.13.5
  - blas=1.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - certifi=2025.10.5
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - decorator=5.2.1
  - docutils=0.21.2
  - executing=2.2.1
  - expat=2.7.1
  - idna=3.7
  - imagesize=1.4.1
  - iniconfig=2.1.0
  - intel-openmp=2025.0.0
  - ipython=9.5.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - maturin=1.9.6
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.5
  - networkx=3.5
  - numexpr=2.11.0
  - numpy=2.3.3
  - numpy-base=2.3.3
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.4
  - patchelf=0.17.2
  - pexpect=4.9.0
  - pip=25.2
  - pluggy=1.5.0
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.23
  - pydata-sphinx-theme=0.16.1
  - pygments=2.19.1
  - pysocks=1.7.1
  - pytest=8.4.2
  - python=3.13.2
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - readline=8.3
  - requests=2.32.5
  - roman-numerals-py=3.1.0
  - scipy=1.16.2
  - setuptools=72.1.0
  - six=1.17.0
  - snowballstemmer=3.0.1
  - soupsieve=2.5
  - sphinx=8.2.3
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=2.0.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tk=8.6.15
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - wheel=0.45.1
