[package]
name = "causal-hub-python"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "causal_hub"
crate-type = ["cdylib"]

[dependencies]
approx.workspace = true
causal-hub = { path = "../causal-hub" }
dry.workspace = true
numpy = "^0.25"
paste.workspace = true
pyo3 = { version = "^0.25", features = ["extension-module"] }
rand.workspace = true
rand_xoshiro = "^0.7"
rayon.workspace = true
