[package]
name = "causal-hub-python"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "causal_hub"
crate-type = ["cdylib"]

[dependencies]
causal-hub = { path = "../causal-hub" }
numpy = "0.24.0"
pyo3 = { version = "0.24.0", features = ["extension-module"] }
