name: causal-hub
channels:
  - defaults
dependencies:
  - alabaster=0.7.16
  - babel=2.16.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - certifi=2025.10.5
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - docutils=0.21.2
  - expat=2.7.1
  - idna=3.7
  - imagesize=1.4.1
  - iniconfig=2.1.0
  - intel-openmp=2025.0.0
  - jinja2=3.1.6
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libmpdec=4.0.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - markupsafe=3.0.2
  - maturin=1.9.4
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.5
  - networkx=3.5
  - numexpr=2.11.0
  - numpy=2.3.3
  - numpy-base=2.3.3
  - openssl=3.0.18
  - packaging=25.0
  - pandas=2.3.3
  - patchelf=0.17.2
  - pip=25.2
  - pluggy=1.5.0
  - pthread-stubs=0.3
  - pycparser=2.23
  - pygments=2.19.1
  - pysocks=1.7.1
  - pytest=8.4.2
  - python=3.13.0
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - readline=8.3
  - requests=2.32.5
  - roman-numerals-py=3.1.0
  - scipy=1.16.2
  - setuptools=72.1.0
  - six=1.17.0
  - snowballstemmer=3.0.1
  - sphinx=8.2.3
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=2.0.0
  - sqlite=3.50.2
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tk=8.6.15
  - tzdata=2025b
  - urllib3=2.5.0
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
