name: python-test

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x64
        python: ["3.10", "3.11", "3.12", "3.13"]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/openblas_build
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.platform.runner }}-${{ matrix.platform.target }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ matrix.platform.runner }}-${{ matrix.platform.target }}-${{ hashFiles('Cargo.lock') }}
            ${{ matrix.platform.runner }}-${{ matrix.platform.target }}-
            ${{ matrix.platform.runner }}-
      - name: Set up system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: true
          python-version: ${{ matrix.python }}
      - name: Build
        run: |
          conda install maturin
          maturin develop \
            --release \
            --no-default-features \
            --features=pyo3/extension-module,pyo3/abi3-py310,backend/openblas-static
        env:
          OPENBLAS_TARGET: GENERIC
          DYNAMIC_ARCH: 1
      - name: Test
        run: |
          conda install pytest
          pytest

  windows:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: windows-latest
            target: x64
        python: ["3.10", "3.11", "3.12", "3.13"]
    defaults:
      run:
        shell: pwsh -Command "& '{0}'"
    steps:
      - uses: actions/checkout@v4
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            C:\vcpkg
            ~\.cargo\registry
            ~\.cargo\git
            target
          key: ${{ matrix.platform.runner }}-${{ matrix.platform.target }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ matrix.platform.runner }}-${{ matrix.platform.target }}-${{ hashFiles('Cargo.lock') }}
            ${{ matrix.platform.runner }}-${{ matrix.platform.target }}-
            ${{ matrix.platform.runner }}-
      - name: Set env variables
        run: |
          "RUSTFLAGS=-C target-feature=+crt-static" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "SCCACHE_GHA_ENABLED=true" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "VCPKG_DEFAULT_TRIPLET=${{ matrix.platform.target }}-windows-static" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "VCPKGRS_TRIPLET=${{ matrix.platform.target }}-windows-static" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Build OpenBLAS
        run: |
          vcpkg integrate install
          vcpkg install openblas --overlay-ports=.vcpkg/ports
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          architecture: ${{ matrix.platform.target }}
          auto-activate-base: true
          activate-environment: true
          python-version: ${{ matrix.python }}
      - name: Build
        run: |
          conda install maturin
          maturin develop `
            --release `
            --no-default-features `
            --features=pyo3/extension-module,pyo3/abi3-py310,backend/openblas-system
      - name: Test
        run: |
          conda install pytest
          pytest

  macos:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: macos-latest
            target: aarch64
        python: ["3.10", "3.11", "3.12", "3.13"]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Application Support/openblas_build
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.platform.runner }}-${{ matrix.platform.target }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ matrix.platform.runner }}-${{ matrix.platform.target }}-${{ hashFiles('Cargo.lock') }}
            ${{ matrix.platform.runner }}-${{ matrix.platform.target }}-
            ${{ matrix.platform.runner }}-
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: true
          python-version: ${{ matrix.python }}
      - name: Build
        run: |
          conda install maturin
          maturin develop \
            --release \
            --no-default-features \
            --features=pyo3/extension-module,pyo3/abi3-py310,backend/accelerate-system
      - name: Test
        run: |
          conda install pytest
          pytest
