name: python-test

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

env:
  SCCACHE_GHA_ENABLED: true
  RUST_WRAPPER: sccache

jobs:
  linux:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-22.04
            target: x86_64
          - runner: ubuntu-22.04
            target: x86
        python: ["3.10", "3.11", "3.12", "3.13"]
    defaults:
      run:
        shell: bash -el {0}
        working-directory: python
    steps:
      - uses: actions/checkout@v4
      - name: Set up sccache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Set up system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: true
          python-version: ${{ matrix.python }}
      - name: Build
        run: |
          conda install maturin
          maturin develop --release
        env:
          OPENBLAS_CC: sccache gcc
          OPENBLAS_FC: sccache gfortran
          OPENBLAS_HOST_CC: sccache gcc
          OPENBLAS_TARGET: GENERIC
          DYNAMIC_ARCH: 1
      - name: Test
        run: |
          conda install pytest
          pytest

  windows:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: windows-latest
            target: x64
          - runner: windows-latest
            target: x86
        python: ["3.10", "3.11", "3.12", "3.13"]
    defaults:
      run:
        shell: pwsh -Command "& '{0}'"
        working-directory: python
    steps:
      - uses: actions/checkout@v4
      - name: Set up sccache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Set env variables
        run: |
          "CMAKE_C_COMPILER_LAUNCHER=sccache" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "CMAKE_CXX_COMPILER_LAUNCHER=sccache" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "CMAKE_Fortran_COMPILER_LAUNCHER=sccache" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "RUSTFLAGS=-C target-feature=+crt-static" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "SCCACHE_GHA_ENABLED=true" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "VCPKG_DEFAULT_TRIPLET=${{ matrix.platform.target }}-windows-static" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "VCPKGRS_TRIPLET=${{ matrix.platform.target }}-windows-static" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Build OpenBLAS
        run: |
          vcpkg integrate install
          vcpkg install openblas --overlay-ports=.vcpkg/ports
        working-directory: ${{ github.workspace }}
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: true
          python-version: ${{ matrix.python }}
      - name: Build
        run: |
          conda install maturin
          maturin develop --release --features=pyo3/extension-module,backend/openblas-system
      - name: Test
        run: |
          conda install pytest
          pytest

  macos:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          # FIXME: Re-enable x86_64 when segmentation fault is fixed.
          # - runner: macos-13
          #   target: x86_64
          - runner: macos-14
            target: aarch64
        python: ["3.10", "3.11", "3.12", "3.13"]
    defaults:
      run:
        shell: bash -el {0}
        working-directory: python
    steps:
      - uses: actions/checkout@v4
      - name: Set up sccache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: true
          python-version: ${{ matrix.python }}
      - name: Build
        run: |
          conda install maturin
          maturin develop --release
      - name: Test
        run: |
          conda install pytest
          pytest
