name: rust-test

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x64
    steps:
      - uses: actions/checkout@v4
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/openblas_build
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.platform.runner }}-${{ matrix.platform.target }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ matrix.platform.runner }}-${{ matrix.platform.target }}-${{ hashFiles('Cargo.lock') }}
            ${{ matrix.platform.runner }}-${{ matrix.platform.target }}-
            ${{ matrix.platform.runner }}-
      - name: Set up system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev
      - name: Build
        run: cargo build --features=openblas-static
      - name: Test
        run: cargo test --features=openblas-static

  windows:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: windows-latest
            target: x64
    steps:
      - uses: actions/checkout@v4
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            C:\vcpkg
            ~\.cargo\registry
            ~\.cargo\git
            target
          key: ${{ matrix.platform.runner }}-${{ matrix.platform.target }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ matrix.platform.runner }}-${{ matrix.platform.target }}-${{ hashFiles('Cargo.lock') }}
            ${{ matrix.platform.runner }}-${{ matrix.platform.target }}-
            ${{ matrix.platform.runner }}-
      - name: Set env variables
        run: |
          "RUSTFLAGS=-C target-feature=+crt-static" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "SCCACHE_GHA_ENABLED=true" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "VCPKG_DEFAULT_TRIPLET=${{ matrix.platform.target }}-windows-static" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "VCPKGRS_TRIPLET=${{ matrix.platform.target }}-windows-static" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Build OpenBLAS
        run: |
          vcpkg integrate install
          vcpkg install openblas --overlay-ports=.vcpkg/ports
      - name: Build
        run: cargo build --features=openblas-system
      - name: Test
        run: cargo test --features=openblas-system

  macos:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: macos-latest
            target: aarch64
    steps:
      - uses: actions/checkout@v4
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Application Support/openblas_build
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.platform.runner }}-${{ matrix.platform.target }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ matrix.platform.runner }}-${{ matrix.platform.target }}-${{ hashFiles('Cargo.lock') }}
            ${{ matrix.platform.runner }}-${{ matrix.platform.target }}-
            ${{ matrix.platform.runner }}-
      - name: Build
        run: cargo build --features=openblas-static
      - name: Test
        run: cargo test --features=openblas-static
